services:
  app:
    container_name: yz-portal-h3c
    image: yz-portal:x86
    restart: always
    # Ports are now managed by Nginx
    # ports:
    #   - "8001:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:/app/prisma/sqlite.db
    env_file:
      - .env
    volumes:
      # Mount the prisma directory to persist the SQLite database and migrations
      - ./prisma:/app/prisma

  nginx:
    image: nginx:stable-alpine
    container_name: yz-portal-nginx
    restart: always
    ports:
      - "12800:80" # Main App Entrance (Host 8001 -> Container 80)
      - "12810:8080" # Proxy Entrance (Host 10088 -> Container 10088)
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
