worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
}

http {
        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        gzip on;

        upstream nextjs_server {
          # 在 docker-compose.dev.yml 中，Next.js 服务名为 "dev"，容器内端口为 3000
          server dev:3000;
        }

        server {
          listen 80;
          server_name localhost;

          location / {
            proxy_pass http://nextjs_server;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host:$server_port;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
        }

        # 浩鲸平台代理 (用户请求的 10088 端口)
        server {
          listen 8080;  
          server_name localhost;

          location / {
            proxy_pass https://lab.iwhalecloud.com;
            proxy_set_header Host lab.iwhalecloud.com;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # 解决 SSL 握手问题（如果有）
            proxy_ssl_server_name on;
          }
        }
}
