user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

stream {
  upstream mysql_backend {
    server 127.0.0.1:3306;
  }

  # server 
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        # server_tokens off;

        # server_names_hash_bucket_size 64;
        # server_name_in_redirect off;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # SSL Settings
        ##

        # ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3; # Dropping SSLv3, ref: POODLE
        # ssl_prefer_server_ciphers on;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;

        ##
        # Upstream Configs
        ##

        upstream nextjs_server {
          server 127.0.0.1:8001;
        }

        upstream nextjs_server_tianjing {
          server 127.0.0.1:8002;
        }

        upstream hj_server {
          server lab.iwhalecloud.com;
        }

        upstream dots_server {
          server 39.175.132.230:35036;
        }

        ##
        # Server Configs
        ##

        server {
          listen 80;
          server_name 39.175.132.230;

          location / {
            proxy_pass http://nextjs_server;
         
          }

          location /dots/ {
            rewrite ^/dots/(.*) /$1 break;
            proxy_pass http://39.175.132.230:35036;
            proxy_set_header Host 39.175.132.230:35036;
          }
        }

        server {
          listen 9000;
          server_name 39.175.132.230;

          location / {
            proxy_pass http://nextjs_server_tianjing;
          }

          location /dots/ {
            rewrite ^/dots/(.*) /$1 break;
            proxy_pass http://39.175.132.230:35036;
            proxy_set_header Host 39.175.132.230:35036;
          }
        }

         # 浩鲸平台代理
        server {
          listen 10080;  
          server_name localhost;

          location / {
            proxy_pass https://lab.iwhalecloud.com;
            proxy_set_header Host lab.iwhalecloud.com;
          }
        }

        # dots 代理
        server {
          listen 6001;
          server_name localhost;

          location / {
            proxy_pass http://39.175.132.230:35036;
            proxy_set_header Host 39.175.132.230:35036;
          }
        }
}

