user www-data;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules-enabled/*.conf;

events {
        worker_connections 768;
        # multi_accept on;
}

stream {
  upstream mysql_backend {
    server 127.0.0.1:3306;
  }

  # server 
}

http {

        ##
        # Basic Settings
        ##

        sendfile on;
        tcp_nopush on;
        types_hash_max_size 2048;
        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        ##
        # Logging Settings
        ##

        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        ##
        # Gzip Settings
        ##

        gzip on;

        ##
        # Virtual Host Configs
        ##

        include /etc/nginx/conf.d/*.conf;
        include /etc/nginx/sites-enabled/*;

        ##
        # Stream Configs
        ##

        upstream api_backend {
          server 127.0.0.1:8001/api;
        }


        ##
        # Server Configs
        ##

        server {
          listen 80;
          server_name 39.175.132.230;

          location / {
            default_type  application/json;
            return 200 '{"status":"ok"}'; 
          }

          location /api/ {
            proxy_pass http://api_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          }
        }

        # 浩鲸平台代理
        server {
            listen 6002;  
            server_name localhost;
                    
            location / {
              proxy_pass https://lab.iwhalecloud.com;
              proxy_set_header Host lab.iwhalecloud.com;
            }
        }

        # dots 代理
        server {
            listen 6001;
            server_name localhost;

            location / {
              proxy_pass http://39.175.132.230:35036;
              proxy_set_header Host 39.175.132.230:35036;
            }
        }

}